apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kdv47y20f-python
  janus-idp.io/tekton: kdv47y20f-python
  backstage.io/kubernetes-id: kdv47y20f-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kdv47y20f-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
