apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kdv47y20f-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kdv47y20f-python 
  name: kdv47y20f-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kdv47y20f-python 
